"""
Project Pukar - Backend Machine Learning & Intelligence Services
Provides unified scoring, regex rule evaluation, Groq LLM extraction, and Priority Engine fusion.
"""

from .briefing import brief, derive_recommended_resources, generate_templated_headline
from .contracts import (
    AIReasoningBreakdown,
    Briefing,
    Category,
    CorrelationVerdict,
    DecryptedSOSPayload,
    EmergencyCategory,
    Entities,
    EscalationResult,
    EscalationState,
    ExtractedEntities,
    FalseAlarmResult,
    GroqTriageResult,
    Language,
    MobilityStatus,
    NeedCategory,
    NormalizedText,
    ReasoningBreakdown,
    ResourceCategory,
    ScoreResult,
    ScoringResult,
    Severity,
    SeverityAssessment,
    SeverityLevel,
    SignedSOSHeader,
)
from .cache import (
    TextHashResponseCache,
    cache_response,
    clear_response_cache,
    get_cache_stats,
    get_cached_response,
    get_response_cache,
)
from .correlate import IncidentCorrelator, correlate, embed
from .extract import RuleBasedEntityExtractor, extract
from .false_alarm import false_alarm, load_false_alarm_config
from .groq_client import GroqClient, GroqErrorCode, GroqExecutionError
from .guard import (
    GUARD_SYSTEM_INSTRUCTION,
    UNTRUSTED_DATA_END,
    UNTRUSTED_DATA_START,
    SanitizationResult,
    get_guard_system_instruction,
    guard_and_wrap,
    sanitize,
    validate_schema,
    wrap_untrusted_data,
)
from .meter import (
    GroqUsageMeter,
    get_usage_meter,
    get_usage_summary,
    record_usage,
    reset_usage_meter,
)
from .normalize import TextNormalizer, clear_cache, detect_language, normalize
from .observability import (
    ObservabilityManager,
    ReportTrace,
    get_recent_traces,
    intelligence_health,
    record_report_trace,
    redact_secrets,
    reset_observability_metrics,
)
from .priority_engine import PriorityEngine
from .regex_engine import RegexEngine
from .scorer import Scorer, score, score_async
from .trend import escalation, load_trend_config

__all__ = [
    "AIReasoningBreakdown",
    "Briefing",
    "Category",
    "CorrelationVerdict",
    "DecryptedSOSPayload",
    "EmergencyCategory",
    "Entities",
    "EscalationResult",
    "EscalationState",
    "ExtractedEntities",
    "FalseAlarmResult",
    "GUARD_SYSTEM_INSTRUCTION",
    "GroqClient",
    "GroqErrorCode",
    "GroqExecutionError",
    "GroqTriageResult",
    "GroqUsageMeter",
    "IncidentCorrelator",
    "Language",
    "MobilityStatus",
    "NeedCategory",
    "NormalizedText",
    "ObservabilityManager",
    "PriorityEngine",
    "RegexEngine",
    "ReasoningBreakdown",
    "ReportTrace",
    "ResourceCategory",
    "RuleBasedEntityExtractor",
    "SanitizationResult",
    "ScoreResult",
    "Scorer",
    "ScoringResult",
    "Severity",
    "SeverityAssessment",
    "SeverityLevel",
    "SignedSOSHeader",
    "TextHashResponseCache",
    "TextNormalizer",
    "UNTRUSTED_DATA_END",
    "UNTRUSTED_DATA_START",
    "brief",
    "cache_response",
    "clear_cache",
    "clear_response_cache",
    "correlate",
    "derive_recommended_resources",
    "detect_language",
    "embed",
    "escalation",
    "extract",
    "false_alarm",
    "generate_templated_headline",
    "get_cache_stats",
    "get_cached_response",
    "get_guard_system_instruction",
    "get_recent_traces",
    "get_response_cache",
    "get_usage_meter",
    "get_usage_summary",
    "guard_and_wrap",
    "intelligence_health",
    "load_false_alarm_config",
    "load_trend_config",
    "normalize",
    "record_report_trace",
    "record_usage",
    "redact_secrets",
    "reset_observability_metrics",
    "reset_usage_meter",
    "sanitize",
    "score",
    "score_async",
    "validate_schema",
    "wrap_untrusted_data",
]
